# Generated by Django 3.1.1 on 2020-09-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claimset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patno', models.IntegerField(default=0)),
                ('pubno', models.IntegerField(default=0)),
                ('claim_list', models.CharField(blank=True, max_length=20000, null=True)),
                ('total_claim', models.IntegerField(default=1)),
                ('add112', models.CharField(blank=True, max_length=10000, null=True)),
                ('obj', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
    ]
