# Generated by Django 3.1.1 on 2020-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimset',
            name='add112',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimset',
            name='claim_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimset',
            name='obj',
            field=models.TextField(blank=True, null=True),
        ),
    ]
